### ISSUE TITLE
Print issue for polygons in Google Maps

### ISSUE THREAD

**Issue by devumair** [selemxmn/ngx-print#118] opened 2021-06-01 13:22 UTC
when I'm printing the google map with the polygon it shows only map without polygon, whereas when I checked it via Ctrl+P (print command) it prints the map with the polygon

**Comment by broem** [comment] 2021-06-03 01:13
Hey, thanks for using ngx-print. 

Could you provide a little context around what the issue is and how to reproduce it? We have an [issue template](https://github.com/selemxmn/ngx-print/blob/692b64a272aa191ac87b6c3bacc4f844e2f1756d/.github/ISSUE_TEMPLATE/bug_report.md)  that many use so we can better resolve the problem.

**Comment by broem** [comment] 2021-06-28 16:52
closing for lack of clarity

**Closed by broem** 2021-06-28 16:52 UTC
